# Generated by Django 4.2.7 on 2023-12-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginForm',
        ),
        migrations.DeleteModel(
            name='UserRegistrationForm',
        ),
    ]
